<template>
      <div class="admin-dashboard">
          <h2>Admin Dashboard</h2>

              <div class="requests-review">
                    <h3>Pending Donations Review</h3>
                          <table class="admin-table">
                                  <thead>
                                            <tr>
                                                        <th>Product</th>
                                                                    <th>Category</th>
                                                                                <th>Quantity</th>
                                                                                            <th>Location</th>
                                                                                                        <th>Action</th>
                                                                                                                  </tr>
                                                                                                                          </thead>
                                                                                                                                  <tbody>
                                                                                                                                            <tr v-for="donation in pendingDonations" :key="donation.id">
                                                                                                                                                        <td>{{ donation.productName }}</td>
                                                                                                                                                                    <td>{{ donation.category }}</td>
                                                                                                                                                                                <td>{{ donation.quantity }}</td>
                                                                                                                                                                                            <td>{{ donation.location }}</td>
                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                      <button class="btn-approve" @click="updateStatus(donation.id, 'Approved')">Approve</button>
                                                                                                                                                                                                                                    <button class="btn-reject" @click="updateStatus(donation.id, 'Rejected')">Reject</button>
                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                        </table>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                              </template>

                                                                                                                                                                                                                                                                              <script setup>
                                                                                                                                                                                                                                                                              import { ref, onMounted } from 'vue'

                                                                                                                                                                                                                                                                              const pendingDonations = ref([])

                                                                                                                                                                                                                                                                              const fetchPending = async () => {
                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                    const rawUrl = 'https://raw.githubusercontent.com/esraaelshamy246-afk/medical-donation-platform/1e59da960820c93cd04e517325623065eca2cba1/db.json'
                                                                                                                                                                                                                                                                                        const res = await fetch(rawUrl)
                                                                                                                                                                                                                                                                                            const data = await res.json()
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    pendingDonations.value = (data.donations || []).filter(d => d.status === 'Pending')
                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                          console.error('Error fetching pending donations:', error)
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            const updateStatus = (id, newStatus) => {
                                                                                                                                                                                                                                                                                                              pendingDonations.value = pendingDonations.value.filter(d => d.id !== id)
                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                              onMounted(() => {
                                                                                                                                                                                                                                                                                                                fetchPending()
                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                </script>

                                                                                                                                                                                                                                                                                                                <style scoped>
                                                                                                                                                                                                                                                                                                                .admin-dashboard {
                                                                                                                                                                                                                                                                                                                  padding: 30px;
                                                                                                                                                                                                                                                                                                                    background: #081b29;
                                                                                                                                                                                                                                                                                                                      color: #fff;
                                                                                                                                                                                                                                                                                                                        min-height: 100vh;
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                        .admin-table {
                                                                                                                                                                                                                                                                                                                          width: 100%;
                                                                                                                                                                                                                                                                                                                            margin-top: 20px;
                                                                                                                                                                                                                                                                                                                              border-collapse: collapse;
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                              .admin-table th, .admin-table td {
                                                                                                                                                                                                                                                                                                                                padding: 12px;
                                                                                                                                                                                                                                                                                                                                  border: 1px solid #0ef;
                                                                                                                                                                                                                                                                                                                                    text-align: center;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                    .btn-approve {
                                                                                                                                                                                                                                                                                                                                      background: #00ff88;
                                                                                                                                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                                                                                                                          padding: 6px 15px;
                                                                                                                                                                                                                                                                                                                                            margin-right: 5px;
                                                                                                                                                                                                                                                                                                                                              border-radius: 4px;
                                                                                                                                                                                                                                                                                                                                                cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                  font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                  .btn-reject {
                                                                                                                                                                                                                                                                                                                                                    background: #ff4d4d;
                                                                                                                                                                                                                                                                                                                                                      color: #fff;
                                                                                                                                                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                                                                                                                                          padding: 6px 15px;
                                                                                                                                                                                                                                                                                                                                                            border-radius: 4px;
                                                                                                                                                                                                                                                                                                                                                              cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                                