<template>
      <div class="user-dashboard">
          <div class="header-info">
                <h2>Welcome, {{ currentUserInfo.fullName || 'User' }}</h2>
                      <p class="user-type">Account Type: {{ currentUserInfo.accountType || 'Individual' }}</p>
                          </div>
                              
                                  <div class="stats-grid">
                                        <DashboardCard title="Total Donations" :value="myDonations.length" icon="bx bxs-donate-blood" color="#0ef" />
                                              <DashboardCard title="Approved Donations" :value="approvedCount" icon="bx bx-check-circle" color="#00ff88" />
                                                    <DashboardCard title="My Requests" :value="myRequests.length" icon="bx bx-list-plus" color="#ffaa00" />
                                                        </div>

                                                            <div class="section-box">
                                                                  <h3>Recent Donations</h3>
                                                                        <table class="custom-table" v-if="myDonations.length > 0">
                                                                                <thead>
                                                                                          <tr>
                                                                                                      <th>Product Name</th>
                                                                                                                  <th>Category</th>
                                                                                                                              <th>Quantity</th>
                                                                                                                                          <th>Expiry Date</th>
                                                                                                                                                      <th>Status</th>
                                                                                                                                                                </tr>
                                                                                                                                                                        </thead>
                                                                                                                                                                                <tbody>
                                                                                                                                                                                          <tr v-for="item in myDonations" :key="item.id">
                                                                                                                                                                                                      <td>{{ item.productName }}</td>
                                                                                                                                                                                                                  <td>{{ item.category }}</td>
                                                                                                                                                                                                                              <td>{{ item.quantity }}</td>
                                                                                                                                                                                                                                          <td>{{ item.expiryDate }}</td>
                                                                                                                                                                                                                                                      <td>
                                                                                                                                                                                                                                                                    <span :class="['badge', item.status.toLowerCase().replace(' ', '_')]">
                                                                                                                                                                                                                                                                                    {{ item.status }}
                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                </tbody>
                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                            <p v-else class="empty-msg">No donations found for your account yet.</p>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                  </template>

                                                                                                                                                                                                                                                                                                                                                  <script setup>
                                                                                                                                                                                                                                                                                                                                                  import { ref, computed, onMounted } from 'vue'
                                                                                                                                                                                                                                                                                                                                                  import DashboardCard from '@/components/dashboard/DashboardCard.vue'

                                                                                                                                                                                                                                                                                                                                                  const myDonations = ref([])
                                                                                                                                                                                                                                                                                                                                                  const myRequests = ref([])
                                                                                                                                                                                                                                                                                                                                                  const currentUserInfo = ref({})

                                                                                                                                                                                                                                                                                                                                                  const approvedCount = computed(() => {
                                                                                                                                                                                                                                                                                                                                                    return myDonations.value.filter(d => d.status === 'Approved').length
                                                                                                                                                                                                                                                                                                                                                    })

                                                                                                                                                                                                                                                                                                                                                    const fetchAndCombineData = async () => {
                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                          const rawUrl = 'https://raw.githubusercontent.com/esraaelshamy246-afk/medical-donation-platform/1e59da960820c93cd04e517325623065eca2cba1/db.json'
                                                                                                                                                                                                                                                                                                                                                              const res = await fetch(rawUrl)
                                                                                                                                                                                                                                                                                                                                                                  const remoteData = await res.json()

                                                                                                                                                                                                                                                                                                                                                                      const localUsers = JSON.parse(localStorage.getItem('registered_users') || '[]')
                                                                                                                                                                                                                                                                                                                                                                          const allUsers = [...(remoteData.users || []), ...localUsers]

                                                                                                                                                                                                                                                                                                                                                                              const loggedInSession = JSON.parse(localStorage.getItem('user') || '{}')

                                                                                                                                                                                                                                                                                                                                                                                  if (loggedInSession && loggedInSession.email) {
                                                                                                                                                                                                                                                                                                                                                                                        const foundUser = allUsers.find(u => u.email === loggedInSession.email)
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                    if (foundUser) {
                                                                                                                                                                                                                                                                                                                                                                                                            currentUserInfo.value = foundUser
                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                          currentUserInfo.value = loggedInSession
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                      const localDonations = JSON.parse(localStorage.getItem('user_donations') || '[]')
                                                                                                                                                                                                                                                                                                                                                                                                                                            const allDonations = [...(remoteData.donations || []), ...localDonations]
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const localRequests = JSON.parse(localStorage.getItem('user_requests') || '[]')
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const allRequests = [...(remoteData.requests || []), ...localRequests]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const userId = currentUserInfo.value.id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                myDonations.value = allDonations.filter(d => d.donorId === userId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      myRequests.value = allRequests.filter(r => r.requesterId === userId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Error syncing dynamic data:', error)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onMounted(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fetchAndCombineData()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <style scoped>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .user-dashboard {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 30px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: #081b29;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            min-height: 100vh;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .header-info {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              margin-bottom: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .header-info h2 {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                font-size: 28px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .user-type {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: #aaa;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-size: 14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .stats-grid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: grid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              margin: 25px 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .section-box {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: rgba(255, 255, 255, 0.05);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border-radius: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: 1px solid #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .custom-table {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border-collapse: collapse;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin-top: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .custom-table th, .custom-table td {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text-align: left;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border-bottom: 1px solid rgba(255,255,255,0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .badge {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 4px 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border-radius: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-size: 12px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-transform: capitalize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .badge.pending { background: #ffaa00; color: #000; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .badge.approved { background: #00ff88; color: #000; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .badge.rejected { background: #ff4d4d; color: #fff; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .empty-msg {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin-top: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: #888;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                font-style: italic;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                