<template>
      <div class="login-wrapper">
          <form v-if="step === 'login'" @submit.prevent="handleLogin">
                <div class="input-box">
                        <input type="email" v-model="form.email" required />
                                <label>Email</label>
                                        <i class="bx bxs-envelope"></i>
                                              </div>

                                                    <div class="input-box">
                                                            <input type="password" v-model="form.password" required />
                                                                    <label>Password</label>
                                                                            <i class="bx bxs-lock-alt"></i>
                                                                                  </div>

                                                                                        <div v-if="errorMessage" class="error-msg">
                                                                                                {{ errorMessage }}
                                                                                                      </div>

                                                                                                            <div class="forgot-link" v-if="showForgotOption">
                                                                                                                    <a href="#" @click.prevent="startForgotPassword">Forgot Password?</a>
                                                                                                                          </div>

                                                                                                                                <button type="submit" class="btn">Login</button>

                                                                                                                                      <div class="logreg-link">
                                                                                                                                              <p>Don't have an account? <a href="#" @click.prevent="$emit('switchToRegister')">Sign Up</a></p>
                                                                                                                                                    </div>
                                                                                                                                                        </form>

                                                                                                                                                            <form v-else-if="step === 'verify_code'" @submit.prevent="handleVerifyCode">
                                                                                                                                                                  <p class="info-text">
                                                                                                                                                                          A verification code was sent to <strong>{{ form.email }}</strong>
                                                                                                                                                                                </p>
                                                                                                                                                                                      
                                                                                                                                                                                            <div class="code-alert">
                                                                                                                                                                                                    🔑 Simulated Email Code: <strong>{{ generatedCode }}</strong>
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                <div class="input-box">
                                                                                                                                                                                                                        <input type="text" v-model="userEnteredCode" maxlength="6" required />
                                                                                                                                                                                                                                <label>Enter 6-digit Code</label>
                                                                                                                                                                                                                                        <i class="bx bx-key"></i>
                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                    <div v-if="errorMessage" class="error-msg">
                                                                                                                                                                                                                                                            {{ errorMessage }}
                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                        <button type="submit" class="btn">Verify & Login</button>
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                    <div class="logreg-link">
                                                                                                                                                                                                                                                                                            <p><a href="#" @click.prevent="step = 'login'">Back to Login</a></p>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        </template>

                                                                                                                                                                                                                                                                                                        <script setup>
                                                                                                                                                                                                                                                                                                        import { reactive, ref } from 'vue'
                                                                                                                                                                                                                                                                                                        import { useRouter } from 'vue-router'

                                                                                                                                                                                                                                                                                                        const router = useRouter()
                                                                                                                                                                                                                                                                                                        defineEmits(['switchToRegister'])

                                                                                                                                                                                                                                                                                                        const form = reactive({
                                                                                                                                                                                                                                                                                                          email: '',
                                                                                                                                                                                                                                                                                                            password: ''
                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                            const step = ref('login')
                                                                                                                                                                                                                                                                                                            const errorMessage = ref('')
                                                                                                                                                                                                                                                                                                            const showForgotOption = ref(false)
                                                                                                                                                                                                                                                                                                            const generatedCode = ref('')
                                                                                                                                                                                                                                                                                                            const userEnteredCode = ref('')
                                                                                                                                                                                                                                                                                                            const foundUser = ref(null)

                                                                                                                                                                                                                                                                                                            const handleLogin = async () => {
                                                                                                                                                                                                                                                                                                              errorMessage.value = ''
                                                                                                                                                                                                                                                                                                                showForgotOption.value = false

                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                      const rawUrl = 'https://raw.githubusercontent.com/esraaelshamy246-afk/medical-donation-platform/1e59da960820c93cd04e517325623065eca2cba1/db.json'
                                                                                                                                                                                                                                                                                                                          const res = await fetch(rawUrl)
                                                                                                                                                                                                                                                                                                                              const remoteData = await res.json()

                                                                                                                                                                                                                                                                                                                                  const localUsers = JSON.parse(localStorage.getItem('registered_users') || '[]')
                                                                                                                                                                                                                                                                                                                                      const allUsers = [...(remoteData.users || []), ...localUsers]

                                                                                                                                                                                                                                                                                                                                          const user = allUsers.find(u => u.email.toLowerCase() === form.email.toLowerCase())

                                                                                                                                                                                                                                                                                                                                              if (!user) {
                                                                                                                                                                                                                                                                                                                                                    errorMessage.value = "Email doesn't exist. Please Sign Up to create an account!"
                                                                                                                                                                                                                                                                                                                                                          return
                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                  if (user.password && user.password !== form.password) {
                                                                                                                                                                                                                                                                                                                                                                        errorMessage.value = "Incorrect password!"
                                                                                                                                                                                                                                                                                                                                                                              showForgotOption.value = true
                                                                                                                                                                                                                                                                                                                                                                                    foundUser.value = user
                                                                                                                                                                                                                                                                                                                                                                                          return
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                  localStorage.setItem('user', JSON.stringify(user))
                                                                                                                                                                                                                                                                                                                                                                                                      router.push('/dashboard')

                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Login error:', error)
                                                                                                                                                                                                                                                                                                                                                                                                                errorMessage.value = "Error connecting to server. Try again."
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                  const startForgotPassword = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                    generatedCode.value = Math.floor(100000 + Math.random() * 900000).toString()
                                                                                                                                                                                                                                                                                                                                                                                                                      step.value = 'verify_code'
                                                                                                                                                                                                                                                                                                                                                                                                                        errorMessage.value = ''
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        const handleVerifyCode = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                          if (userEnteredCode.value === generatedCode.value) {
                                                                                                                                                                                                                                                                                                                                                                                                                              localStorage.setItem('user', JSON.stringify(foundUser.value))
                                                                                                                                                                                                                                                                                                                                                                                                                                  router.push('/dashboard')
                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                        errorMessage.value = "Invalid verification code. Check the code and try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                          </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <style scoped>
                                                                                                                                                                                                                                                                                                                                                                                                                                          .input-box {
                                                                                                                                                                                                                                                                                                                                                                                                                                            position: relative;
                                                                                                                                                                                                                                                                                                                                                                                                                                              width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                height: 45px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  margin: 15px 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  .input-box input {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: transparent;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            outline: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              border-bottom: 2px solid #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding-right: 23px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-size: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-weight: 500;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transition: .5s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .input-box input:focus,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .input-box input:valid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border-bottom-color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .input-box label {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            position: absolute;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              top: 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                left: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transform: translateY(-50%);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font-size: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pointer-events: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition: .5s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .input-box input:focus ~ label,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .input-box input:valid ~ label {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            top: -5px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .input-box i {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                position: absolute;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    right: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transform: translateY(-50%);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-size: 18px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .btn {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 45px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: transparent;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 2px solid #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    outline: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border-radius: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          font-size: 16px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin-top: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .error-msg {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: #ff4d4d;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font-size: 13px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      margin: 10px 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .forgot-link {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-align: right;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin-bottom: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .forgot-link a {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                font-size: 13px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text-decoration: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .forgot-link a:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text-decoration: underline;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .logreg-link {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-size: 14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #fff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin: 15px 0 5px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .logreg-link p a {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text-decoration: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  font-weight: 600;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .info-text {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: #ccc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      font-size: 14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-bottom: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .code-alert {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: rgba(0, 238, 255, 0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: 1px solid #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: #0ef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border-radius: 8px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text-align: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-bottom: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          font-size: 14px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          