<template>
      <form @submit.prevent="handleRegister">
          <div class="input-box">
                <input type="text" v-model="form.fullName" required>
                      <label>Full Name</label>
                            <i class='bx bxs-user'></i>
                                </div>
                                    
                                        <div class="input-box">
                                              <input type="email" v-model="form.email" required>
                                                    <label>Email</label>
                                                          <i class='bx bxs-envelope'></i>
                                                              </div>

                                                                  <div class="input-box">
                                                                        <input type="password" v-model="form.password" required>
                                                                              <label>Password</label>
                                                                                    <i class='bx bxs-lock-alt'></i>
                                                                                        </div>

                                                                                            <div class="select-box">
                                                                                                  <select v-model="form.accountType" required>
                                                                                                          <option value="Individual">Individual</option>
                                                                                                                  <option value="Organization">Organization</option>
                                                                                                                        </select>
                                                                                                                            </div>

                                                                                                                                <button type="submit" class="btn">Sign Up</button>
                                                                                                                                    
                                                                                                                                        <div class="logreg-link">
                                                                                                                                              <p>Already have an account? <a href="#" @click.prevent="$emit('switchToLogin')">Login</a></p>
                                                                                                                                                  </div>
                                                                                                                                                    </form>
                                                                                                                                                    </template>

                                                                                                                                                    <script setup>
                                                                                                                                                    import { reactive } from 'vue'
                                                                                                                                                    import { useRouter } from 'vue-router'

                                                                                                                                                    const router = useRouter()
                                                                                                                                                    defineEmits(['switchToLogin'])

                                                                                                                                                    const form = reactive({
                                                                                                                                                      fullName: '',
                                                                                                                                                        email: '',
                                                                                                                                                          password: '',
                                                                                                                                                            accountType: 'Individual'
                                                                                                                                                            })

                                                                                                                                                            const handleRegister = () => {
                                                                                                                                                              const newUser = {
                                                                                                                                                                  id: Date.now(),
                                                                                                                                                                      fullName: form.fullName,
                                                                                                                                                                          email: form.email,
                                                                                                                                                                              accountType: form.accountType,
                                                                                                                                                                                  role: 'user'
                                                                                                                                                                                    }

                                                                                                                                                                                      const existingUsers = JSON.parse(localStorage.getItem('registered_users') || '[]')
                                                                                                                                                                                        existingUsers.push(newUser)
                                                                                                                                                                                          localStorage.setItem('registered_users', JSON.stringify(existingUsers))

                                                                                                                                                                                            localStorage.setItem('user', JSON.stringify(newUser))
                                                                                                                                                                                              router.push('/dashboard')
                                                                                                                                                                                              }
                                                                                                                                                                                              </script>

                                                                                                                                                                                              <style scoped>
                                                                                                                                                                                              .input-box {
                                                                                                                                                                                                position: relative;
                                                                                                                                                                                                  width: 100%;
                                                                                                                                                                                                    height: 45px;
                                                                                                                                                                                                      margin: 15px 0;
                                                                                                                                                                                                      }

                                                                                                                                                                                                      .input-box input {
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                          height: 100%;
                                                                                                                                                                                                            background: transparent;
                                                                                                                                                                                                              border: none;
                                                                                                                                                                                                                outline: none;
                                                                                                                                                                                                                  border-bottom: 2px solid #fff;
                                                                                                                                                                                                                    padding-right: 23px;
                                                                                                                                                                                                                      font-size: 15px;
                                                                                                                                                                                                                        color: #fff;
                                                                                                                                                                                                                          font-weight: 500;
                                                                                                                                                                                                                            transition: .5s;
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                            .input-box input:focus,
                                                                                                                                                                                                                            .input-box input:valid {
                                                                                                                                                                                                                              border-bottom-color: #0ef;
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              .input-box label {
                                                                                                                                                                                                                                position: absolute;
                                                                                                                                                                                                                                  top: 50%;
                                                                                                                                                                                                                                    left: 0;
                                                                                                                                                                                                                                      transform: translateY(-50%);
                                                                                                                                                                                                                                        font-size: 15px;
                                                                                                                                                                                                                                          color: #fff;
                                                                                                                                                                                                                                            pointer-events: none;
                                                                                                                                                                                                                                              transition: .5s;
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                              .input-box input:focus ~ label,
                                                                                                                                                                                                                                              .input-box input:valid ~ label {
                                                                                                                                                                                                                                                top: -5px;
                                                                                                                                                                                                                                                  color: #0ef;
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                  .input-box i {
                                                                                                                                                                                                                                                    position: absolute;
                                                                                                                                                                                                                                                      top: 50%;
                                                                                                                                                                                                                                                        right: 0;
                                                                                                                                                                                                                                                          transform: translateY(-50%);
                                                                                                                                                                                                                                                            font-size: 18px;
                                                                                                                                                                                                                                                              color: #fff;
                                                                                                                                                                                                                                                                transition: .5s;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                .input-box input:focus ~ i,
                                                                                                                                                                                                                                                                .input-box input:valid ~ i {
                                                                                                                                                                                                                                                                  color: #0ef;
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                  .select-box {
                                                                                                                                                                                                                                                                    margin: 15px 0;
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                    .select-box select {
                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                        padding: 8px 10px;
                                                                                                                                                                                                                                                                          background: #081b29;
                                                                                                                                                                                                                                                                            color: #0ef;
                                                                                                                                                                                                                                                                              border: 1px solid #0ef;
                                                                                                                                                                                                                                                                                border-radius: 5px;
                                                                                                                                                                                                                                                                                  outline: none;
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                  .btn {
                                                                                                                                                                                                                                                                                    position: relative;
                                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                                        height: 45px;
                                                                                                                                                                                                                                                                                          background: transparent;
                                                                                                                                                                                                                                                                                            border: 2px solid #0ef;
                                                                                                                                                                                                                                                                                              outline: none;
                                                                                                                                                                                                                                                                                                border-radius: 40px;
                                                                                                                                                                                                                                                                                                  cursor: pointer;
                                                                                                                                                                                                                                                                                                    font-size: 16px;
                                                                                                                                                                                                                                                                                                      color: #fff;
                                                                                                                                                                                                                                                                                                        font-weight: 600;
                                                                                                                                                                                                                                                                                                          z-index: 1;
                                                                                                                                                                                                                                                                                                            overflow: hidden;
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            .btn::before {
                                                                                                                                                                                                                                                                                                              content: '';
                                                                                                                                                                                                                                                                                                                position: absolute;
                                                                                                                                                                                                                                                                                                                  top: -100%;
                                                                                                                                                                                                                                                                                                                    left: 0;
                                                                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                                                                        height: 300%;
                                                                                                                                                                                                                                                                                                                          background: linear-gradient(#081b29, #0ef, #081b29, #0ef);
                                                                                                                                                                                                                                                                                                                            z-index: -1;
                                                                                                                                                                                                                                                                                                                              transition: .5s;
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                              .btn:hover::before {
                                                                                                                                                                                                                                                                                                                                top: 0;
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                .logreg-link {
                                                                                                                                                                                                                                                                                                                                  font-size: 14px;
                                                                                                                                                                                                                                                                                                                                    color: #fff;
                                                                                                                                                                                                                                                                                                                                      text-align: center;
                                                                                                                                                                                                                                                                                                                                        margin: 15px 0 5px;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        .logreg-link p a {
                                                                                                                                                                                                                                                                                                                                          color: #0ef;
                                                                                                                                                                                                                                                                                                                                            text-decoration: none;
                                                                                                                                                                                                                                                                                                                                              font-weight: 600;
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                              .logreg-link p a:hover {
                                                                                                                                                                                                                                                                                                                                                text-decoration: underline;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                                                                                                